In [2]:
import pandas as pd

df=pd.read_csv("sample_data.csv")
print(df)

df.isnull().sum()

      name  gender       city passed
0     aman    male      delhi    yes
1    priya  female     mumbai    yes
2    rahul    male  bangalore     no
3   anjali  female     mumbai    yes
4     ravi    male      delhi    yes
5    meera  female    chennai     no
6    arjun     NaN  bangalore    yes
7     neha  female      delhi    yes
8    imran    male    chennai     no
9    sneha  female     mumbai    yes
10     raj    male    chennai    yes
11   divya     NaN      delhi     no
12   kabir    male     mumbai    yes
13  simran  female  bangalore    yes
14   karan     NaN      delhi    NaN
15   pooja  female     mumbai    NaN
16  rakesh    male    chennai    NaN
17    isha  female      delhi     no
18   rohit     NaN      delhi    yes
19   deepa  female  bangalore    yes


name      0
gender    4
city      0
passed    3
dtype: int64

In [3]:
#filling missing values for ML to work properly

#df[df['gender'].isnull()]
df[df.isnull().any(axis=1)]
#for passed column, fill NaN with mode
df['passed'].fillna(df['passed'].mode()[0], inplace=True)

#for gender column
df['gender'].fillna(df['gender'].mode()[0], inplace=True)

print(df)

      name  gender       city passed
0     aman    male      delhi    yes
1    priya  female     mumbai    yes
2    rahul    male  bangalore     no
3   anjali  female     mumbai    yes
4     ravi    male      delhi    yes
5    meera  female    chennai     no
6    arjun  female  bangalore    yes
7     neha  female      delhi    yes
8    imran    male    chennai     no
9    sneha  female     mumbai    yes
10     raj    male    chennai    yes
11   divya  female      delhi     no
12   kabir    male     mumbai    yes
13  simran  female  bangalore    yes
14   karan  female      delhi    yes
15   pooja  female     mumbai    yes
16  rakesh    male    chennai    yes
17    isha  female      delhi     no
18   rohit  female      delhi    yes
19   deepa  female  bangalore    yes


C:\Users\Admin\AppData\Local\Temp\ipykernel_5812\3094195500.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['passed'].fillna(df['passed'].mode()[0], inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_5812\3094195500.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.



In [6]:
#converting categorical data(gender and passed columns) to numerical data
from sklearn.preprocessing import LabelEncoder

df1=df.copy()
le=LabelEncoder()

df1["gender_encoded"]=le.fit_transform(df1["gender"])
df1["passed_encoded"]=le.fit_transform(df1["passed"])

print("Encoded data is\n: ")
print(df1[['name', 'gender', 'gender_encoded', 'passed', 'passed_encoded']])

Encoded data is
: 
      name  gender  gender_encoded passed  passed_encoded
0     aman    male               1    yes               1
1    priya  female               0    yes               1
2    rahul    male               1     no               0
3   anjali  female               0    yes               1
4     ravi    male               1    yes               1
5    meera  female               0     no               0
6    arjun  female               0    yes               1
7     neha  female               0    yes               1
8    imran    male               1     no               0
9    sneha  female               0    yes               1
10     raj    male               1    yes               1
11   divya  female               0     no               0
12   kabir    male               1    yes               1
13  simran  female               0    yes               1
14   karan  female               0    yes               1
15   pooja  female               0    yes            

In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv("sample_data.csv")

df_encoded=pd.get_dummies(df1, columns=['city'], dtype=int) # using dtype to convert boolean value into integer
print("\none-hot encoded data (city): ")
print(df_encoded)


one-hot encoded data (city): 
      name  gender passed  gender_encoded  passed_encoded  city_bangalore  \
0     aman    male    yes               1               1               0   
1    priya  female    yes               0               1               0   
2    rahul    male     no               1               0               1   
3   anjali  female    yes               0               1               0   
4     ravi    male    yes               1               1               0   
5    meera  female     no               0               0               0   
6    arjun  female    yes               0               1               1   
7     neha  female    yes               0               1               0   
8    imran    male     no               1               0               0   
9    sneha  female    yes               0               1               0   
10     raj    male    yes               1               1               0   
11   divya  female     no               0    

In [9]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(df1[['gender_encoded', 'passed_encoded']])

print("Scaled data is\n: ")
print(x_scaled)

# MinMaxScaler example
min_max_scaler = MinMaxScaler()
x_scaled= min_max_scaler.fit_transform(df1[['gender_encoded', 'passed_encoded']])

print("MinMax Scaled data is\n: ")
print(x_scaled)

Scaled data is
: 
[[ 1.36277029  0.57735027]
 [-0.73379939  0.57735027]
 [ 1.36277029 -1.73205081]
 [-0.73379939  0.57735027]
 [ 1.36277029  0.57735027]
 [-0.73379939 -1.73205081]
 [-0.73379939  0.57735027]
 [-0.73379939  0.57735027]
 [ 1.36277029 -1.73205081]
 [-0.73379939  0.57735027]
 [ 1.36277029  0.57735027]
 [-0.73379939 -1.73205081]
 [ 1.36277029  0.57735027]
 [-0.73379939  0.57735027]
 [-0.73379939  0.57735027]
 [-0.73379939  0.57735027]
 [ 1.36277029  0.57735027]
 [-0.73379939 -1.73205081]
 [-0.73379939  0.57735027]
 [-0.73379939  0.57735027]]
MinMax Scaled data is
: 
[[1. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]]


In [10]:
#linear regression 
'''
1. finds a pattern in old data
2.staright line
3.predicts future values

syntax:
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model.fit(X, y)
model.predict([[value]])
'''

'\n1. finds a pattern in old data\n2.staright line\n3.predicts future values\n\nsyntax:\nfrom sklearn.linear_model import LinearRegression\nmodel= LinearRegression()\nmodel.fit(X, y)\nmodel.predict([[value]])\n'

In [ ]:
#linear regression example
from sklearn.linear_model import LinearRegression

X= [[1], [2], [3], [4], [5]]
y= [[40], [50], [65], [75], [90]]

model= LinearRegression()

model.fit(X, y)

hours= eval(input("enter how many hours you studied: "))
predicted_marks=model.predict([[hours]])

print(f"based on your", hours, "hours you may score around", predicted_marks)

#three points to remember
# 1. its not about the line, its about the story 
# 2. 5 rows use start
# 3. accuracy is not always the goal, sometimes its about the story it tells

In [2]:
# classification
#logistic regression
from sklearn.linear_model import LogisticRegression

X=[[1], [2], [3], [4], [5]] #hours studied ye h hamara input
y=[0,0,1,1,1] #result 0 aaya toh fail, 1 aaya to pass

model=LogisticRegression()

model.fit(X, y)

hours= eval(input("enter how many hours you studied: "))
result= model.predict([[hours]])[0]  # passing extra zero taki label nikal kr aaye 0 ya 1 

if result == 1:
    print(f"Based on your", hours, "hours studied You are likely to pass")

else:
    print(f"Based on your", hours, "hours studied You are likely to fail")

enter how many hours you studied:  2


Based on your 2 hours studied You are likely to fail


In [1]:
#K nearest neighbors

from sklearn.neighbors import KNeighborsClassifier

X=[[180,7], #fruit weight in grams, size in cm 180 grams, and 7 cm size
  [200, 7.5],
  [250, 8],
  [300, 8.5],
  [330, 9],
  [360, 9.5]]

#0= apple, 1=orange
y=[0,0,0,1,1,1]

model= KNeighborsClassifier(n_neighbors=3)

model.fit(X, y)
weight=eval(input("enter the weight in grams"))
size=eval(input("enter the size in centimeters"))

prediction=model.predict([[weight, size]])[0]

if prediction == 0:
    print("this is likely an Apple")

else:
    print("this is likely an orange")

this is likely an Apple


In [6]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

X=[[7, 2], #apple
  [8, 3], #apple
  [9, 8], #orange
  [10, 9]] #orange

y=[0,0,1,1] #0= apple, 1=orange
model= DecisionTreeClassifier()

model.fit(X, y)

#color_shade= 1-3= red, 4-10=orange color
size=eval(input("enter the fruits size in cm"))
color_shade=eval(input("enter the color shade (1-10): "))

result=model.predict([[size,color_shade]])[0]

if result == 0:
    print("this is likely an Apple")

else:
    ("this is likely an orange")

'''
three secret:

1. machine ko jitna ache se aap clear rule doge unta acha se wo kaam kregi
2. trees can be too smart, mtlb jitna zyda aap training data doge, tree jo hai utna zyda khud se memorize krte jyegi
3. it is easy to explain to boss or colleague
'''

enter the fruits size in cm 8.5
enter the color shade (1-10):  4


this is likely an Apple


In [4]:
#mastering model evaluation
#classification Metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#true answers(what actually happened)
y_true=[1,0,1,1,0,1,0]
#model prediction(what it guessed)
y_pred=[1,0,1,0,0,1,1]

#evaluation
print("Accuracy: ", accuracy_score(y_true, y_pred))

print("Precision: ", precision_score(y_true, y_pred)) #agr maine 10 mei se 8 logon ka prediction kiya tha, toh unn 8 mei se kitne prediction 
                                                        #acutally mei sahi the

print("Recall: ", recall_score(y_true, y_pred)) # actual mei kitne real positives mujhe mile

print("F1 score: ", f1_score(y_true, y_pred)) # agr mai precision and recall ko mix krdun toh kya number niklega

'''
three points to remember:
1. accuracy is not enough if data is unbalanced
2.precision ka use kriye when False alarm are dangerous
3. aap recall ka use kriye when missing case is dangerous'''

Accuracy:  0.7142857142857143
Precision:  0.75
Recall:  0.75
F1 score:  0.75


'\nthree points to remember:\n1. accuracy is not enough if data is unbalanced\n2.precision ka use kriye when False alarm are dangerous\n3. aap recall ka use kriye when missing case is dangerous'

In [8]:
#Confusion Matrix:
from sklearn.metrics import confusion_matrix

y_true=[1,0,1,1,0,1,0,0,1,0]

y_pred=[1,0,1,0,0,1,1,0,1,0]

cm=confusion_matrix(y_true, y_pred)
print("confusion matrix:\n ", cm)

#explaination of answer[[4 1] [1 4]] in notebook
                    

confusion matrix:
  [[4 1]
 [1 4]]


In [9]:
 #regression metrics: MAE, MSE, RMSE
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

#real score from test result
real_score= [90,60,80,100]

#model guess
predicted_score=[85,70,70,95]

mae=mean_absolute_error(real_score, predicted_score)
mse=mean_squared_error(real_score, predicted_score)
rmse=np.sqrt(mse)

print("MAE: ", mae)
print("MSE: ", mse)
print("RMSE: ", rmse)

MAE:  7.5
MSE:  62.5
RMSE:  7.905694150420948


In [8]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

data=pd.read_csv('student.csv')

X=data[['hours']] #double brackets= 2d input
y=data['score'] #target column

model= LinearRegression()
model.fit(X, y)

predicted_scores=model.predict(X)

#evaluate
mae=mean_absolute_error(y, predicted_scores)
mse=mean_squared_error(y, predicted_scores)
rmse=np.sqrt(mse)

#result
print("Mean Absolute Error (MAE): ", mae)
print("Mean Squared Error (MSE): ", mse)
print("Root Mean Squared Error (RMSE): ", rmse)

new_hour=eval(input("enter the number of hours you studied: "))
new_pred= model.predict([[new_hour]])
print(f"prediction for ", new_hour, "hours is: ", new_pred)

Mean Absolute Error (MAE):  0.6666666666666643
Mean Squared Error (MSE):  0.6285714285714282
Root Mean Squared Error (RMSE):  0.7928249671720916


prediction for  7 hours is:  [86.4]


c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [9]:
'''
three step formula to remember:

1. khudse pucho, kya X and y (jo input and guess hai) woh numeric hai? agar haan toh scatter plot draw krna h for relationship
2. is one column a category? barplot ya countplot daldo
3. kya apko ek distribution shape dekhna hai? histogram ya kde plot ya box plot daldo

'''

'\nthree step formula to remember:\n\n1. khudse pucho, kya X and y (jo input and guess hai) woh numeric hai? agar haan toh scatter plot draw krna h for relationship\n2. is one column a category? barplot ya countplot daldo\n3. kya apko ek distribution shape dekhna hai? histogram ya kde plot ya box plot daldo\n\n'